
spring:
  application:
        name: gapsi-e-commerce
      
#Testcredentials
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    #url: jdbc:h2:file:${user.dir}/testdb;CACHE_SIZE=8192;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE 
    #url: jdbc:h2:file:./data/demo
    username: sa
    password: 
    driverClassName: org.h2.Driver
    #For test this is not recommendable
  jpa:   
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
#This is for the show in console or the browser
  h2:
    console:
        enabled: true
        settings.trace: false
        settings.web-allow-others: false
    #http://localhost:8090/h2-console
     
server: 
  port: 8090
  
app:
  version: ^project.version^
  name: ^project.name^